//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApplicationmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_info
    {
        public int id { get; set; }
        public string email_id { get; set; }
        public string username { get; set; }
        public string passcode { get; set; }
        public Nullable<int> student_id { get; set; }
    
        public virtual signup_info signup_info { get; set; }
    }
}
