//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApplicationmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signup_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public signup_info()
        {
            this.login_info = new HashSet<login_info>();
        }
    
        public int id { get; set; }
        public int student_id { get; set; }
        public string student_name { get; set; }
        public Nullable<long> postal_code { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login_info> login_info { get; set; }
    }
}
